name: Build and Publish Docker Image
on:
  push:
   tags:
    - '*'

jobs:
  build-and-publish-django:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: vamsi434
        password: ${{ secrets.GIT_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t my-image:${{ github.ref }} .
        docker tag my-image:${{ github.ref }} ghcr.io/vamsi434/my-image:${{ github.ref }}

    - name: Push Docker image to GitHub Packages
      run: |
        docker push ghcr.io/vamsi434/my-image:${{ github.ref }}
