name: Build and Deploy with Docker

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-app:${{ github.sha }}

    - name: Run Docker container
      uses: actions-hub/docker/cli@master
      with:
        image: my-app:${{ github.sha }}
        ports: '80:80'
